[package]
name = "fun_render"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
default = ["offscreen", "volumetric_clouds"]
benchmarks = []
cloud_diagnostics = ["render_diagnostics"]
diagnostics = ["game_shared/diagnostics"]
dlss = ["bevy/dlss"]
dx12_dlss_native = ["dx12_native_interop", "dep:fun_dx12_dlss"]
dx12_mesh_shader_experiment = ["dx12_native_interop"]
dx12_native_interop = ["wgpu/dx12", "dep:windows-core"]
dx12_native_object_names = ["dx12_native_interop", "dep:windows"]
force_disable_dlss = ["bevy/force_disable_dlss"]
offscreen = []
render_diagnostics = [
    "diagnostics",
    "bevy/debug",
    "bevy/track_location",
    "bevy/pbr_debug_diagnostics",
    "bevy/meshlet_debug_diagnostics",
]
volumetric_clouds = []
winit_presentation = []

[dependencies]
bevy.workspace = true
fun_dx12_dlss = { path = "../fun_dx12_dlss", optional = true }
fun_renderer.workspace = true
game_shared = { path = "../game_shared" }
serde.workspace = true
thunder.workspace = true
tracing.workspace = true
wgpu = { version = "29.0.3", default-features = false }

[target.'cfg(windows)'.dependencies]
windows-core = { version = "0.62", optional = true }
windows = { version = "0.62", optional = true, features = ["Win32_Graphics_Direct3D12"] }
