/* @generated by editor-core/src/schema.rs. Do not edit by hand. */

export type EventLevel = "info" | "warning" | "error";

export type EcsDomain = "client" | "server" | "shared";

export type ProjectCrateRole = "client" | "server" | "shared" | "launcher" | "backend" | "support";

export type EntitySourceKind = "source_bsn" | "client_live" | "server_live" | "shared_schema";

export type EntitySourceFilter = "live" | "bsn" | "both";

export type BsnInvocationKind = "bsn" | "bsn_list";

export type AuthCapability = "read_entities" | "read_components" | "read_resources" | "read_diagnostics" | "control_runtime" | "mutate_entities" | "apply_scene_patch" | "execute_server_code" | "execute_client_code" | "persist_iteration";

export type ClientBuildProfile = "debug" | "debug_diagnostics" | "release" | "force_disable_dlss";

export type RuntimeKind = "client" | "server";

export type RuntimeAttachRequest = { target: RuntimeKind, inspector_addr: string, };

export type SourceLocation = { line: number, column: number, };

export type SourceSpan = { path: string, byte_start: number, byte_end: number, start: SourceLocation, end: SourceLocation, };

export type Diagnostic = { code: string, level: EventLevel, message: string, target_path: string | null, hosted_instance_id: string | null, };

export interface CommandResult<T> { ok: boolean; value: T | null; diagnostics: Array<Diagnostic>; }

export type LauncherMode = "hidden" | "launcher" | "editor";

export type LauncherGameStatus = "local" | "online" | "unavailable";

export type JoinableGame = { id: string, title: string, summary: string, region: string, status: LauncherGameStatus, players_online: number, max_players: number, latency_ms: number | null, project_id: string, build_profile: ClientBuildProfile, accent: string, };

export type AuthorizedProject = { id: string, display_name: string, root_path: string, crate_count: number, bsn_scene_count: number, edit_authorized: boolean, authorization_summary: string, last_opened_label: string, };

export type LauncherAuthorization = { can_join_game: boolean, can_host_local: boolean, can_open_project: boolean, can_edit_project: boolean, can_resume_editor: boolean, can_stop_runtime: boolean, capabilities: Array<AuthCapability>, reason: string | null, };

export type LauncherActiveRuntime = { instance_id: string, project_id: string, kind: ViewportKind, status: ViewportStatus, pid: number | null, editor_owned: boolean, inspector_state: string, game_network_state: string, };

export type RuntimeHostStatus = { launcher_mode: LauncherMode, host_state: string, active_runtime: LauncherActiveRuntime | null, runtime_status: RuntimeStatusSummary, };

export type LauncherState = { launcher_mode: LauncherMode, games: Array<JoinableGame>, projects: Array<AuthorizedProject>, selected_game_id: string | null, selected_project_id: string | null, active_runtime: LauncherActiveRuntime | null, authorization: LauncherAuthorization, runtime_host_status: RuntimeHostStatus, };

export type ProjectReference = { id: string, root_path: string, display_name: string, };

export type MaterialShaderSummary = { id: string, name: string, relative_path: string, absolute_path: string, byte_len: number, modified_unix_ms: number | null, };

export type MaterialShaderCatalog = { project_id: string, project_root: string, shader_roots: Array<string>, default_relative_directory: string, shaders: Array<MaterialShaderSummary>, };

export type MaterialShaderDocument = { summary: MaterialShaderSummary, source: string, diagnostics: Array<Diagnostic>, };

export type MaterialShaderLoadRequest = { project_id: string, relative_path: string, };

export type MaterialShaderSaveRequest = { project_id: string, relative_path: string, source: string, };

export type CommandDescriptor = { id: string, title: string, summary: string, category: string, input_description: string, output_description: string, };

export type EditorEvent = { timestamp: string, command_id: string, level: EventLevel, message: string, target_path: string | null, hosted_instance_id: string | null, };

export type HostedInstanceSummary = { instance_id: string, kind: string, status: string, process_id: number | null, };

export type ProjectCrate = { name: string, manifest_path: string, target_names: Array<string>, role: ProjectCrateRole, domain: EcsDomain | null, };

export type BsnSourceRecord = { id: string, invocation_kind: BsnInvocationKind, domain: EcsDomain | null, file_path: string, span: SourceSpan, scene_function_name: string | null, detected_names: Array<string>, component_type_tokens: Array<string>, };

export type BsnIndexSummary = { revision: number, project_root: string, indexed_roots: Array<string>, records: Array<BsnSourceRecord>, record_count: number, detected_scene_count: number, };

export type ViewportKind = "client" | "preview_renderer";

export type ViewportStatus = "running" | "launched_unembedded" | "stopped";

export type WindowHandleStatus = "embedded" | "window_not_found" | "embedding_failed" | "parent_unavailable" | "unsupported_platform" | "detached";

export type ViewportInstanceSummary = { id: string, project_id: string, kind: ViewportKind, pid: number | null, status: ViewportStatus, window_handle_status: WindowHandleStatus, inspector_addr: string, launch_command: Array<string>, stdout_log_path: string | null, stderr_log_path: string | null, diagnostics: Array<Diagnostic>, };

export type PreviewFrameSummary = { frame_index: number, rgba_byte_len: number, readback_status: string, };

export type PreviewSceneSummary = { scene_id: string, entity_count: number, revision: number, manifest_signature: number, };

export type PreviewRenderTargetSummary = { width: number, height: number, format: string, texture_usages: string, };

export type PreviewRendererStatus = { status: string, scene: PreviewSceneSummary, frame: PreviewFrameSummary, target: PreviewRenderTargetSummary, signature_warning: string | null, };

export type EditorActivationRoute = "editor_shell";

export type EditorActivationSummary = { project_id: string, game_session_id: string, client_pid: number, focused_window: boolean, requested_mode: EditorActivationRoute, viewport: ViewportInstanceSummary | null, };

export type ProjectSummary = { id: string, root_path: string, display_name: string, crates: Array<ProjectCrate>, targets: Array<string>, asset_roots: Array<string>, bsn_roots: Array<string>, bsn_index: BsnIndexSummary, diagnostics: Array<Diagnostic>, current_viewport_status: ViewportInstanceSummary | null, };

export type EntityFilter = { domain: EcsDomain | null, source: EntitySourceFilter | null, query: string | null, };

export type EntitySummary = { id: string, name: string, domains: Array<EcsDomain>, domain: EcsDomain, source_kind: EntitySourceKind, source: string, source_span: SourceSpan | null, components: Array<string>, selectable: boolean, live_snapshot: boolean, revision: number, };

export type ViewportRect = { x: number, y: number, width: number, height: number, scale_factor: number, };

export type AuthSessionSummary = { session_id: string, control_addr: string, token_redacted: boolean, allowed_capabilities: Array<AuthCapability>, expires_unix_ms: number, expired: boolean, };

export type AccountProfileSummary = { subject: string, display_name: string, handle: string, avatar_url: string, authorized: boolean, };

export type BackendAccountMode = "login" | "register";

export type BackendAccountTicketLoginRequest = { email: string, password: string, mode: BackendAccountMode, display_name: string | null, audience: string, requested_capabilities: Array<AuthCapability>, };

export type BackendAuthTicketRequest = { audience: string, requested_capabilities: Array<AuthCapability>, };

export type BackendAuthTicket = { audience: string, backend_base_url: string, subject: string, profile: AccountProfileSummary, capabilities: Array<AuthCapability>, expires_unix_ms: number, ticket_redacted: boolean, };

export type BackendAuthSessionState = { authenticated: boolean, backend_base_url: string, profile: AccountProfileSummary | null, ticket: BackendAuthTicket | null, };

export type RuntimeConnectionStatus = { state: string, detail: string, authenticated: boolean, last_error: string | null, protocol_version: number | null, schema_revision: number | null, diagnostic_schema_revision: number | null, last_heartbeat_unix_ms: number | null, subscriptions: Array<string>, backpressure: string, reconnect_state: string, };

export type RuntimeStatusSummary = { client_process: RuntimeConnectionStatus, client_inspector: RuntimeConnectionStatus, server_process: RuntimeConnectionStatus, server_inspector: RuntimeConnectionStatus, game_network: RuntimeConnectionStatus, update_rate_limit_hz: number, };

export type EditorDiagnosticRecord = { sequence: number, kind: string, target: string, level: EventLevel, message: string, source: string | null, frame_index: number | null, };

export type RuntimeDiagnosticsSnapshot = { target: RuntimeKind | null, records: Array<EditorDiagnosticRecord>, latest_counters: Array<EditorDiagnosticRecord>, latest_frame_profile: EditorFrameProfileSnapshot | null, dropped_packets: number, };

export type EditorFrameProfileSnapshot = { target: string, frame: number, frame_ns: number, main_thread_ns: number, render_thread_ns: number, gpu_ns: number, rows: Array<EditorFrameProfileRow>, };

export type EditorFrameProfileRow = { name: string, target: string, depth: number, duration_ns: number, self_ns: number, count: number, source: string | null, };

export type UiComponentSchemaModel = { stable_type_id: number, component_kind: number, display_label: string, mutability: string, serialization_policy: string, replication_policy: string, ui_group: string, ui_widget: string, importance: string, diagnostic_label: string, };

export type RuntimeInstanceSummary = { id: string, project_id: string, kind: RuntimeKind, pid: number | null, process_status: string, inspector_status: string, authenticated: boolean, inspector_addr: string, launch_command: Array<string>, stdout_log_path: string | null, stderr_log_path: string | null, diagnostics: Array<Diagnostic>, };

export type EntityStreamOpenRequest = { filter: EntityFilter | null, page_size: number | null, overscan_rows: number | null, synthetic_count: number | null, };

export type LiveEntityStreamOpenRequest = { target: RuntimeKind | null, filter: EntityFilter | null, page_size: number | null, overscan_rows: number | null, };

export type EntityStreamCursor = { cursor: string, revision: number, total_rows: number, page_size: number, overscan_rows: number, };

export type EntityStreamPageRequest = { cursor: string, offset: number, limit: number | null, };

export type EntityRowSummary = { id: string, name: string, domain: EcsDomain, source_kind: EntitySourceKind, source: string, source_span: SourceSpan | null, component_count: number, selectable: boolean, live_snapshot: boolean, revision: number, };

export type EntityStreamPage = { cursor: string, revision: number, offset: number, limit: number, total_rows: number, rows: Array<EntityRowSummary>, };

export type ComponentSummary = { name: string, value_preview: string | null, source: string | null, component_kind: number | null, schema_label: string | null, mutability: string | null, replication_policy: string | null, ui_group: string | null, ui_widget: string | null, importance: string | null, raw_payload_bytes: number, read_only: boolean, };

export type SourcePreview = { path: string, start_line: number, end_line: number, text: string, };

export type EntityDetails = { row: EntityRowSummary, components: Array<ComponentSummary>, resources: Array<ComponentSummary>, source_preview: SourcePreview | null, };

export type TransformVector3 = { x: number, y: number, z: number, };

export type TransformRotation = { x: number, y: number, z: number, w: number, };

export type TransformPatchRequest = { entity_id: string, base_revision: number, translation: TransformVector3, rotation: TransformRotation, scale: TransformVector3, persist_iteration: boolean, };

export type TransformPatchResult = { entity_id: string, status: string, world_revision: number, applied_ops: number, conflict_count: number, persistence: string, diagnostics: Array<string>, };

export type EntityStreamCloseSummary = { cursor: string, closed: boolean, };

export type EditorStatus = { stage_name: string, target_fps_path: string, fun_workspace_exists: boolean, expected_fun_crates: Array<string>, ui_stack: string, rust_service_status: string, retired_engine_demo_status: string, current_project: ProjectReference | null, client_viewport_status: string, runtime_status: RuntimeStatusSummary, auth_session: AuthSessionSummary, };

