[package]
name = "fun-renderer"
edition.workspace = true
version.workspace = true

[lib]
name = "fun_renderer"

[lints]
workspace = true

[features]
default = ["bevy_ecs", "fun_renderer_new_core", "fun_renderer_dx12"]
bevy_ecs = ["dep:bevy_camera", "dep:bevy_ecs", "dep:bevy_transform"]
fun_lux_hybrid_gi = ["fun_lux/fun_lux_hybrid_gi"]
fun_lux_many_light = ["fun_lux/fun_lux_many_light"]
fun_lux_virtual_shadows = ["fun_lux/fun_lux_virtual_shadows"]
fun_renderer_cef_gpu_only = []
fun_renderer_dlss = []
fun_renderer_dx12 = []
fun_renderer_experimental_ml = []
fun_renderer_frame_generation = []
fun_renderer_fsr = []
fun_renderer_legacy = []
fun_renderer_new_core = []
fun_renderer_upscale = []
fun_renderer_vulkan = []

[dependencies]
bevy_camera = { workspace = true, optional = true }
bevy_ecs = { workspace = true, optional = true }
bevy_transform = { workspace = true, optional = true }
fun_lux.workspace = true
fun_scene.workspace = true
