[package]
name = "fun_host"
edition.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
fun_editor_core = { path = "../fun_editor_core" }
fun_ecs.workspace = true
fun_scene = { package = "fun-scene", path = "../fun-scene" }
reqwest.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
zeroize.workspace = true
