param(
    [string]$Profile = "default.dx12.immediate",
    [switch]$PlanOnly,
    [switch]$Release,
    [switch]$StaticBevy,
    [switch]$NoClient,
    [switch]$Launcher,
    [switch]$CefUi,
    [switch]$CefUiDx12AcceleratedPaint,
    [ValidateSet("default", "disabled", "cpu", "auto", "d3d11on12")]
    [string]$CefPaintTransport = "default",
    [switch]$CefAcceleratedStrict,
    [ValidateRange(2, 5)]
    [int]$CefGpuRingDepth = 3,
    [switch]$CefCopyDirtyRects,
    [switch]$CefDebugTimings,
    [switch]$RenderDiagnostics,
    [switch]$TraceDiagnostics,
    [switch]$RenderProfileVerbose,
    [switch]$FrameTimeDiagnostics,
    [switch]$BenchmarkLogMinimal,
    [switch]$LogStreamVerbose,
    [switch]$LogNetVerbose,
    [switch]$LogRenderVerbose,
    [switch]$Maximized,
    [switch]$DisableFpsOverlay,
    [switch]$EnableFpsOverlay,
    [switch]$SolariDebugDirectVisibility,
    [switch]$EnableDx12DlssRr,
    [switch]$DisableDlssRr,
    [switch]$DisableSolari,
    [switch]$DisableMeshlets,
    [switch]$DisableClouds,
    [string]$RtSampleDirect = "",
    [string]$RtSampleIndirect = "",
    [string]$RtSampleReflections = "",
    [string]$RtSurfaceCache = "",
    [string]$RtMegaGeom = "",
    [string]$RtOpacityMask = "",
    [string]$RtHair = "",
    [string]$RtAsyncReadback = "",
    [string]$RtValidation = "",
    [switch]$RenderUnknownVendor,
    [string]$RenderVendorEmulation = "",
    [string]$SolariArch = "budgeted",
    [int]$SolariTargetFps = 144,
    [int]$SolariFrameBudgetNs = 6944444,
    [int]$SolariGpuBudgetNs = 3000000,
    [string]$SolariVisualTarget = "competitive",
    [string]$SolariDenoiseMode = "balanced-fast",
    [string]$SolariInternalScale = "1.0",
    [int]$SolariBlasCompactionVertices = 0,
    [string]$SolariDebugOverlay = "",
    [string]$CloudQuality = "",
    [string]$CloudInternalScale = "",
    [string]$CloudTemporal = "",
    [string]$CloudShadows = "",
    [string]$CloudProfile = "",
    [string]$CloudDebugOverlay = "",
    [string]$RenderGeometryPolicy = "hybrid",
    [int]$MeshletMinTriangles = 512,
    [ValidateSet(0, 1, 2, 4, 8)]
    [int]$StreamRenderPrepBudgetMs = 0,
    [ValidateRange(0, 1000000)]
    [int]$StreamRenderPrepMaxChunksPerFrame = 0,
    [int]$WindowWidth = 0,
    [int]$WindowHeight = 0,
    [string]$RenderBackend = "dx12",
    [string]$PresentMode = "immediate",
    [int]$RenderMaxFrameLatency = 0,
    [int]$FrameTimeDiagnosticInterval = 60,
    [int]$FrameTimeDiagnosticMinNs = 0,
    [int]$FrameTimeDiagnosticMaxDepth = 10,
    [int]$FrameTimeDiagnosticTopChildren = 16,
    [int]$FrameTimeDiagnosticTopSpans = 32,
    [switch]$FrameTimeDiagnosticRowEvents,
    [int]$StartupDelaySeconds = 2,
    [switch]$DryRun,
    [string]$OutputRoot = ""
)

$ErrorActionPreference = "Stop"
. (Join-Path $PSScriptRoot "FunBench.Compat.ps1")

Invoke-FunBenchCompat `
    -Subcommand "run-stack" `
    -BoundParameters $PSBoundParameters `
    -ActualParameters @(
        "Profile",
        "PlanOnly",
        "Release",
        "StaticBevy",
        "NoClient",
        "Launcher",
        "CefUi",
        "CefUiDx12AcceleratedPaint",
        "CefPaintTransport",
        "CefAcceleratedStrict",
        "CefGpuRingDepth",
        "CefCopyDirtyRects",
        "CefDebugTimings",
        "RenderDiagnostics",
        "TraceDiagnostics",
        "FrameTimeDiagnostics",
        "RenderBackend",
        "PresentMode",
        "RenderMaxFrameLatency",
        "StartupDelaySeconds",
        "DryRun",
        "OutputRoot"
    )
