[package]
name = "game_client"
edition.workspace = true
version.workspace = true

[features]
default = ["dlss"]
benchmarks = []
bevy_debug = ["bevy/debug"]
dlss = ["bevy/dlss"]
force_disable_dlss = ["bevy/force_disable_dlss"]

[dependencies]
avian3d.workspace = true
bevy.workspace = true
bevy_quinnet.workspace = true
game_shared = { path = "../game_shared" }
log.workspace = true
thunder.workspace = true
tracing.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "client_costs"
harness = false
required-features = ["benchmarks"]
